### ISSUE TITLE
a few changes 

### ISSUE THREAD

**Issue by lghinet** [zefoy/ngx-perfect-scrollbar#1] opened 2016-09-21 11:17 UTC
when u`re using the router, the scrollbar does not detect the height change of the router outlet content, i ve made a few changes, and it is working ok, if u may consider adding them : 

`template: '<div class="inner-scroll"><ng-content></ng-content></div>',`
and in the ngDoCheck function 
`var height = this.elementRef.nativeElement.getElementsByClassName("inner-scroll")[0].offsetHeight;`

the this.elementRef.nativeElement. always has the same height even if the content has changed ,
with that inner scroll div, i get the right new height

**Comment by sconix** [comment] 2016-09-21 11:22
Thanks, I will look into this.

**Comment by sconix** [comment] 2016-09-21 13:07
I could not reproduce the problem. With correct styles the scrollbar did work inside router outlet as well. Perhaps you could give me some example code which reproduces the problem.

**Comment by lghinet** [comment] 2016-09-21 13:34
did you wrap it like this, or each component has its own perfect-scrollbar tag 
`<perfect-scrollbar class="full-width">
           <router-outlet></router-outlet>
</perfect-scrollbar>`
maybe my style is wrong, but does make sense to get the same height of the perfect-scrollbar  element, 
`this.elementRef.nativeElement.offsetHeight;`
regardless of the content , as long as it scrolls

**Comment by sconix** [comment] 2016-09-21 13:44
Ah I misunderstood you a bit, so you are placing the router outlet inside the ps element and not the otherway around :) I will test and verify that case later today.

**Comment by sconix** [comment] 2016-09-21 14:20
Now when I stop to actually think about it your fix makes sense, but we also need to check for the change in scroller height as well as the content height. I will add a fix for this and release 0.6.1.

**Closed as completed** 2016-09-21 14:46 UTC
Labels: bug
