### ISSUE TITLE
Scrollbar is hidden and only shows when mousing over!!!

### ISSUE THREAD

**Issue by nigel-dewar** [zefoy/ngx-perfect-scrollbar#183] opened 2018-05-04 01:09 UTC
Is there no way to make the scrollbar stay visible when not moused over?

If so, where is this controlled from. 

Im using angular 5 with angular-cli.

I cant even see any way to control this through css, if there is a css file for this directive, I have no idea where it is

Cheers

**Comment by sconix** [comment] 2018-05-04 08:07
That's how the default styles of perfect-scrollbar are made. You can always overwrite the styles with your own styles.

As the readme says for directive you need to import the css file yourself. And its normal css so you can either load your own css file or just overwrite the parts that you want.

**Comment by sconix** [comment] 2018-05-09 12:41
I plan to add some sort of input or special class for the next 6.1.0 release that one can more easily have permanently showing scrollbars.

**Comment by sconix** [comment] 2018-05-09 12:45
This is duplicate of #179 so closing this.

**Closed as completed by sconix** 2018-05-09 12:45 UTC
Labels: duplicate
