### ISSUE TITLE
ngx-perfect-scrollbar not working in Angular 5 due to using OpaqueToken

### ISSUE THREAD

**Issue by phorst-incomm** [zefoy/ngx-perfect-scrollbar#109] opened 2017-11-03 15:50 UTC
In Angular 4, OpaqueToken was marked as deprecated. In Angular 5 it was removed, so perfect scrollbar does not work with Angular 5.

Solution: Use InjectionToken instead

**Comment by sconix** [comment] 2017-11-03 20:32
There is a pre release (5.0.0-7) out which works with Angular 5, new official release will be out when new perfect-scrollbar version is released.

**Comment by filipvh** [comment] 2017-11-06 13:43
@sconix  which version is it we are waiting for 1.1.1 ? :)
also
could you not release a 4.8.5 or so with only ng 5 bug fixed?

**Comment by filipvh** [comment] 2017-11-06 15:11
Could you relesa 5.0.0-8 with dependency 
        "perfect-scrollbar": "0.8.0",
it would resolve all current issues

**Comment by filipvh** [comment] 2017-11-06 15:12
5.0.0-9 ... :D

**Comment by filipvh** [comment] 2017-11-06 15:21
0.8.1 :p

**Comment by filipvh** [comment] 2017-11-06 15:44
if so you probably also need to change something in the code that points to the newest css file :p 
and revert that :p

**Comment by filipvh** [comment] 2017-11-06 15:45
... for aot support ...

**Comment by sconix** [comment] 2017-11-06 16:33
I don't get what you mean, there are releases out that work.

**Comment by filipvh** [comment] 2017-11-06 16:42
if i do a install of 5.0.0-8 with angular5
it doesn't work because in the latest perfect-scrollbar the initialize method does not work (missing in the d.ts file?)
so i downgrade it to perfect-scrollbar@0.8.1
and force ngx-perfect-scrollbar to use that
then it complains about missing css if i do a aot build
so i reintroduce the new css file
that seems to work, but is hacky

i made a copy of the 5.0.0-8 'tag'

Changed the dep's

```
"dependencies": {
    "perfect-scrollbar": "^0.8.1",
    "resize-observer-polyfill": "^1.4.0"
  },
  "devDependencies": {
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@types/node": "^8.0.0",
    "@types/perfect-scrollbar": "^0.7.0",
    "angular2-inline-template-style": "~1.1.0",
    "angular2-template-loader": "~0.6.0",
    "awesome-typescript-loader": "~3.2.0",
    "codelyzer": "~3.2.0",
    "core-js": "~2.5.0",
    "cpx": "~1.5.0",
    "node-sass": "~4.5.0",
    "raw-loader": "~0.5.0",
    "rxjs": "^5.5.2",
    "sass-loader": "~6.0.0",
    "string-replace-loader": "~1.3.0",
    "strip-sourcemap-loader": "~0.0.0",
    "stylelint": "~8.1.0",
    "stylelint-config-standard": "~17.0.0",
    "stylelint-order": "~0.7.0",
    "tslint": "~5.7.0",
    "typescript": "~2.5.0",
    "watch": "~1.0.0",
    "webpack": "~3.6.0",
    "zone.js": "^0.8.14"
  },
  "peerDependencies": {
    "@angular/common": ">=5.0.0",
    "@angular/core": ">=5.0.0"
  }
```

and changed the css import in the sass file

`@import '~perfect-scrollbar/dist/css/perfect-scrollbar.min.css';`

and now it all works...

**Comment by filipvh** [comment] 2017-11-06 16:46
it seems in 5.0.0-8 you still use the old way of using perfect-scrollbar
Ps.initialize(this.elementRef.nativeElement, config);
while on newer versions they need you to:

const ps = new PerfectScrollbar(this.elementRef.nativeElement);
or something like that

**Comment by filipvh** [comment] 2017-11-06 16:50
i'll try to look at it later, maybe start with a angular 5 by angular-cli 1.5.0 project ...

**Comment by sconix** [comment] 2017-11-06 19:17
If you would just read my comment bit more carefully. Use 5.0.0-7 not 5.0.0-8.

**Comment by pmsa29** [comment] 2017-11-06 22:57
I tried using 5.0.0-7 and 5.0.0-8 and it doesn't work. 

![2017-11-06_16-56-24](https://user-images.githubusercontent.com/33435711/32468370-8ee4467c-c313-11e7-9baf-73b25ae46b63.png)

**Comment by sconix** [comment] 2017-11-07 06:58
All I can say that 5.0.0-7 works, but you need to clear your node modules so that the newer PS wont be causing any problems.

Anyway new (final) pre-release is coming out today since new version of perfect-scrollbar was just released.

**Comment by filipvh** [comment] 2017-11-07 08:26
:+1:  will be installing that as soon as you publish ^.^

**Comment by hudzenko** [comment] 2017-11-07 11:21
Waiting for new publishing too 👍

**Comment by sconix** [comment] 2017-11-07 21:11
There is now new pre-release 5.0.0-9 which is build using Angular 5 and is fully compatible with it. It also uses perfect-scrollbar 1.x. This is a huge update so check the releases page for breaking changes.

Please report all problems as new issues. I will release the final 5.0.0 during this week.

**Closed as completed by sconix** 2017-11-07 21:11 UTC
Labels: invalid

**Comment by xzegga** [comment] 2018-06-12 00:01
@sconix :( ps with 5.0.0-9 doesn't work with angular 5.2.0

**Comment by sconix** [comment] 2018-06-12 05:51
Why do you want to use so old version? You should use the latest 5.x release with Angular 5.

**Comment by karthickDhanapal** [comment] 2018-08-03 11:08
Hi @sconix 

Hope you are doing good I am facing an issue when i use the ngx perfect scroll bar inside the material tab the scroll for x and y axis are same and there is no change of right and bottom in x axis

![image](https://user-images.githubusercontent.com/33171571/43639910-7b57224e-973b-11e8-8668-cab30811e273.png)

**Comment by karthickDhanapal** [comment] 2018-08-03 17:29
@sconix  

the issue is duplicate of https://github.com/zefoy/ngx-perfect-scrollbar/issues/201
