### ISSUE TITLE
@HostListener/@Output's are triggering Angular change detection

### ISSUE THREAD

**Issue by mtraynham** [zefoy/ngx-perfect-scrollbar#166] opened 2018-03-15 22:15 UTC
I was implementing a scroll on drag feature outside the Angular Zone and noticed that all the [HostListeners and ultimately the Output's](https://github.com/zefoy/ngx-perfect-scrollbar/blob/master/src/lib/perfect-scrollbar.directive.ts#L48) are triggering Angular change detection.

I'm not sure it can be avoided with the current implementation, but it would be nice if these listeners only fired if you actually subscribed to them.

**Comment by sconix** [comment] 2018-03-16 06:56
I am aware of this, but I don't know how to solve this with Angular. One thing I have been thinking is that the scroll events usually would not need to happen in Angular zone so maybe it would help if I would emit the outputs outside of the Angular zone. Not sure if that would help much since afaik the issue is with HostListeners that might already trigger the change detection. Any suggestions are welcome.

**Comment by mtraynham** [comment] 2018-03-16 15:58
It depends on what you actually want to trigger change detection...  Moving the events outside the Angular Zone as element event listeners can still call the `@Output` event emitters and the user would be notified, but it wouldn't trigger change detection.  I guess my question is, do you actually expect anything to be checked on a scroll?  And could we leave that up to the user to mark for change detection?

Personally, I wouldn't mind removing all the `@HostListener`s, I don't really see a use case to check things on scroll.

**Comment by sconix** [comment] 2018-03-16 17:40
This change will be introduced in the next major release which is out in next week or so. I will also add similar optimizations for the components touch / wheel event handling.

**Closed as completed by sconix** 2018-03-16 17:40 UTC
Labels: enhancement
