### ISSUE TITLE
Scroll thumb tremor

### ISSUE THREAD

**Issue by munkk** [zefoy/ngx-perfect-scrollbar#99] opened 2017-10-17 17:14 UTC
Hello, if make scroll-thumb visible through setting opacity attribute (like on the pic for example), and then push Scroll to 0, 100 button, then it starts to shake while moving. Can I somehow get rid of this bug?
![image](https://user-images.githubusercontent.com/13670003/31677306-02637ea2-b373-11e7-8d10-3a31450fd789.png)

**Comment by sconix** [comment] 2017-10-17 17:30
I was able to reproduce it and interestingly it only happens on the directive at least for me. I will study this bit more that why does that happen and can I fix it in the library or if its a bug in perfect-scrollbar. I will post here once I have found the issue.

**Comment by sconix** [comment] 2017-10-17 17:58
I was able to fix this within this library so it will be fixed on the next release which I make as soon as the next release of perfect-scrollbar is out which should be soon. 

The reason for it was the way how perfect-scrollbar default styles / scrollbars work which requires update be called always after programmatic scroll for the bars to update their position. In the current version I do the update call with timeout hence the small tremor.  With current version you can do what the component does, i.e. force the position of the scroll rails relative to the parent element which naturally needs to have position relative etc. You can have a look how the styles are for the component or just wait for next release.

**Comment by munkk** [comment] 2017-10-17 18:08
thanks a lot!

**Comment by sconix** [comment] 2017-11-07 12:00
This should be now fixed in the upcoming release (4.9.2) which is out really soon.

**Closed as completed by sconix** 2017-11-07 12:00 UTC
Labels: bug
