### ISSUE TITLE
Check / add support for AOT

### ISSUE THREAD

**Issue by Merraclius** [zefoy/ngx-perfect-scrollbar#5] opened 2016-11-11 10:48 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Application should compile with Ahead-of-time compilation

#### What is the current behavior?
Failed in compile time with error:
` Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`

#### What are the steps to reproduce?
Try to run AOT using official [guide](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)

#### What is the use-case or motivation for changing an existing behavior?
Without that fix we cannot use that awesome library

#### Which versions are affected?
angular2-perfect-scrollbar - 1.0.0
\@angular\core - 2.1.2
\@angular\compiler-cli - 2.1.2
typescript - 2.0.8

**Comment by sconix** [comment] 2016-11-11 11:13
AOT support is definitely coming, but currently I am bit busy. So I can't say any time when I can fix this, but at least withing this month. Naturally if somebody can make a PR then I will gladly accept that and make a new release.

**Comment by Merraclius** [comment] 2016-11-11 11:24
Cool, thanks for reply.

**Comment by korlu** [comment] 2016-11-17 01:22
Nice library.. but I, too, need AOT support.  Thanks.

**Comment by drakenfly** [comment] 2016-12-13 21:35
I just wanted to ask if there's something going on about the issue. I'm building my project on top of angular-cli and can't upgrade to the last version :/

Note: angular2-perfect-scrollbar is still working with angular-cli beta.20-4, and angular ^2.1.0. Hope this will be fixed soon to upgrade the cli and angular itself.

**Comment by sconix** [comment] 2016-12-16 21:47
I am waiting angular-cli team to get working release out, I have not been able to use the latest after beta.20 since the releases after that seem to have so many problems. When new working release comes out and this needs some changes I will naturally make them, but for now I think the problem is in angular-cli.

I am going to look into AOT support in this month.

**Comment by drakenfly** [comment] 2016-12-20 20:40
Just one thing to mention: Solving the problem is as easy as following:

```
{
  provide: PerfectScrollbarConfig,
  useFactory: (config) => new PerfectScrollbarConfig(config),
  deps: [
    PERFECT_SCROLLBAR_CONFIG
  ]
}
```

change `useFactory: (config) => new PerfectScrollbarConfig(config)` to `useFactory: anyMethodNameYouLike`

and add a function to the end of the file

```
export function anyMethodNameYouLike(config): any {
  return new PerfectScrollbarConfig(config);
}
```

**Comment by sconix** [comment] 2016-12-21 07:19
You mean that fixes AOT? Thanks for the info, I will change that for the release of today.

**Comment by drakenfly** [comment] 2016-12-21 07:29
At least I removed the dependency to ng2-ps, added PS directly as dependency, copied your source files to my-project-root --> "/angular2-perfect-scrollbar/source-files...." and only changed that line. Angular-CLI started working again.

Without that line changed, I got the same error using the source code directly as using it as a dependency.

Tested with cli-beta.22-1 and beta.24.

**Comment by sconix** [comment] 2016-12-21 07:38
Ok, but in a way it makes sense and I can understand my way causing some problems so I will change it anyway. Thanks for letting me know about that change.

**Comment by drakenfly** [comment] 2016-12-21 07:40
I reinstalled angular2-perfect-scrollbar and got the same error. Now I tested to modify the JS-source from your library in node_modules as I did to the typescript-files, but the CLI throws the same error. Maybe I was looking forward too early.

If you have time, please validate if that really fixes the problem before publishing (although I think that this change cannot break anything).

At least, with angular-cli.beta-24, the pipeline is not completely broken anymore!

**Comment by sconix** [comment] 2016-12-21 07:48
Ok, I am trying to get our project building with cli beta.24. When (if) I get it working I will post my findings here and if changes needed will release newer version today.

**Comment by sconix** [comment] 2016-12-25 20:41
The upcoming 2.0.0 version supports latest angular-cli since the library is now AOT compatible. Which means that it also brings support for AOT. The umd bundle is still provided and in addition there is not minified version of the umd bundle.

**Closed as completed by sconix** 2016-12-25 20:41 UTC
Labels: enhancement
